sudo: required
dist: trusty
group: edge
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
addons:
  apt:
    packages:
      - oracle-java8-installer
before_script: cd ltse/
script:
  - javac LTSExtractor.java
